---
#- name: Create docker deploy dir
#  ansible.builtin.file:
#    path: /home/vagrant/task4
#    state: directory
#    mode: '0755'

- name: copy docker image to host
  ansible.builtin.copy:
    src: /home/vagrant/vagrant_tasks/task4/roles/docker-delivery/files/app_v0_1.tar
    dest: /home/vagrant/app_v0_1.tar

- name: copy docker image to host
  ansible.builtin.copy:
    src: /home/vagrant/vagrant_tasks/task4/roles/docker-delivery/files/docker-bundle.tar.gz
    dest: /home/vagrant/docker-bundle.tar.tgz

- name: load container from tarball
  community.docker.docker_image:
    name: app:v.0.1
    load_path: /home/vagrant/app_v0_1.tar
    state: present
    source: load

- name: Unarchive a project dir from bastion
  ansible.builtin.unarchive:
    src: /home/vagrant/docker-bundle.tar.tgz
    dest: /home/vagrant/
    remote_src: yes
