---
- name: build container image
  community.docker.docker_image:
    build:
      path: ./files
    name: app
    tag: v.0.1
    source: build

- name: archive container image as a tarball
  community.docker.docker_image:
    name: app:v.0.1
    archive_path: /home/vagrant/app_v0_1.tar
    source: pull

- name: fetch archived image
  fetch:
    src: /home/vagrant/app_v0_1.tar
    dest: ./files/app_v0_1.tar
    flat: true
