---
# tasks file for docker-delivery
- hosts: docker_hosts
  gather_facts: no
  tasks:
    - name: copy tarball to host
      copy:
        src: ./app_v0_1.tar
        dest: /home/vagrant/app_v0_1.tar

    - name: load container from tarball
      docker_image:
        name: app:v.0.1
        load_path: /home/vagrant/app_v0_1.tar
        state: present
        source: load
