---
- name: copy tarball to host
  copy:
    src: ./files/app_v0_1.tar
    dest: /home/vagrant/app_v0_1.tar
  when: "'build_host' not  in group_names"

- name: load container from tarball
  community.docker.docker_image:
    name: app:v.0.1
    load_path: /home/vagrant/app_v0_1.tar
    state: present
    source: load
  when: "'build_host' not  in group_names"
