---
- name: Create docker deploy dir
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: copy docker image to host
  ansible.builtin.copy:
    src: /home/vagrant/vagrant_tasks/task4/roles/docker-delivery/files/app_v0_2.tar
    dest: "{{ app_dir }}/app_v0_2.tar"

#- name: copy docker image to host
#  ansible.builtin.copy:
#    src: /home/vagrant/vagrant_tasks/task4/roles/docker-delivery/files/docker-bundle.tar.gz
#    dest: /home/vagrant/docker-bundle.tar.tgz

- name: load container from tarball
  community.docker.docker_image:
    name: "{{ image_name }}:{{ image_tag }}"
    load_path: "{{ app_dir }}/app_v0_2.tar"
    state: present
    source: load

#- name: Unarchive a project dir from bastion
#  ansible.builtin.unarchive:
#    src: /home/vagrant/docker-bundle.tar.tgz
#    dest: /home/vagrant/task
#    remote_src: yes
