version: "3.3"
services:
  app:
    build: .
    image: app:v.0.1
    restart: unless-stopped

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
