version: "3.3"
services:
  app:
    build: .
    image: app:v.0.1
    restart: unless-stopped
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/proxy:/etc/nginx/sites-enabled/default.conf:ro
      - ./nginx/cert:/etc/nginx/cert
    expose:
      - "80:80"
      - "443:443"
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
