---
#- name: Iptables flush filter
#  ansible.builtin.iptables:
#    chain: "{{ item }}"
#    flush: yes
#  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

- name: Iptables flush nat
  ansible.builtin.iptables:
    table: nat
    chain: '{{ item }}'
    flush: yes
  with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]

- name: Allow connections on multiple ports from bastion
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: 10.10.0.10
    destination_ports:
      - "80"
      - "443"
      - "22"
    jump: ACCEPT

- name: Allow output connection to bastion
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    destination: 10.10.0.10     
    jump: ACCEPT
