---
# tasks file for ha_proxy
- name: HAProxy | Install package
  yum:
    name: haproxy
    state: present
  tags:
    - haproxy-package
- name: HAProxy | configuration files for ha1
  template:
    src: ../templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - reload haproxy
  tags:
    - haproxy-configuration
- name: HAProxy | start service
  service:
    name: haproxy
    state: running
  tags:
    - haproxy-service
