Vagrant.configure(2) do |config|

  config.vm.define "host1" do |subconfigs|
    subconfigs.vm.box = "centos/7"
    subconfigs.vm.hostname="host1"
    subconfigs.vm.network :private_network, ip: "10.0.2.100"
    subconfigs.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
    subconfigs.vm.provision "shell", inline: <<-SHELL
    yum -y install yum-utils
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin git
    systemctl start docker
    curl -SL https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    usermod -aG docker vagrant
    git clone https://github.com/SergeyKa-cmd/vagrant_tasks.git
    cd /home/vagrant/vagrant_tasks/haproxy-keepalived-docker && docker-compose up -d keepalived-b haproxy-a haproxy-b web-a web-b
    SHELL
  end

  config.vm.define "host2" do |subconfigs|
    subconfigs.vm.box = "centos/7"
    subconfigs.vm.hostname="host2"
    subconfigs.vm.network :private_network, ip: "10.0.2.200"
    subconfigs.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
    subconfigs.vm.provision "shell", inline: <<-SHELL
    yum -y install yum-utils
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin git
    systemctl start docker
    curl -SL https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    usermod -aG docker vagrant
    git clone https://github.com/SergeyKa-cmd/vagrant_tasks.git
    cd /home/vagrant/vagrant_tasks/haproxy-keepalived-docker && docker-compose up -d keepalived-b haproxy-a haproxy-b web-a web-b
    SHELL
  end

  config.ssh.insert_key = false 
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"  

#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "provision.yml"
#  end

end
