---
# tasks file for bind-dns
- name: Install Bind
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - bind9
   - bind9utils
   - dnsutils
  when:
    ansible_os_family == "Debian"

- name: Create a zone directory
  ansible.builtin.file:
    path: /etc/bind/zones
    state: directory
    mode: '0755'

- name: Remove old files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/bind/named.conf.options
    - /etc/bind/named.conf.local
    - /etc/bind/bastion.zone
    - /etc/bind/bastion.zone.rev

- name: Copy named.conf.options file
  ansible.builtin.copy:
    src:  /home/vagrant/vagrant_tasks/task4/roles/bind-dns/files/named.conf.options
    dest: /etc/bind/named.conf.options
    mode: 0644
    owner: root
    group: bind

- name: Copy named.conf.local file
  ansible.builtin.copy:
    src:  /home/vagrant/vagrant_tasks/task4/roles/bind-dns/files/named.conf.local
    dest: /etc/bind/named.conf.local
    mode: 0644
    owner: root
    group: bind

- name: Copy DNS zone file
  ansible.builtin.copy:
    src:  /home/vagrant/vagrant_tasks/task4/roles/bind-dns/files/bastion.zone
    dest: /etc/bind/zones/bastion.zone
    mode: 0644
    owner: root
    group: bind

- name: Copy DNS reverse zone file
  ansible.builtin.copy:
    src:  /home/vagrant/vagrant_tasks/task4/roles/bind-dns/files/bastion.zone.rev
    dest: /etc/bind/zones/bastion.zone.rev
    mode: 0644
    owner: root
    group: bind
  notify:
  - bind restart
