---
# tasks file for bind-dns
- name: Install Bind
  apt:
    name: "{{ item }}"
    state: present
  loop:
   - bind9
   - dnsutils
  when:
    ansible_os_family == "Debian"
  notify:
    - bind systemd
