Vagrant.configure(2) do |config|

  config.vm.define "ha1" do |subconfigs|
    subconfigs.vm.box = "centos/7"
    subconfigs.vm.hostname="host1"
    subconfigs.vm.network :private_network, ip: "10.10.0.10"
    subconfigs.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
    subconfigs.vm.provision "shell", inline: <<-SHELL
    echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
    echo net.ipv4.ip_nonlocal_bind=1 >> /etc/sysctl.conf
    modprobe ip_vs
    SHELL
  end

  config.vm.define "ha2" do |subconfigs|
    subconfigs.vm.box = "centos/7"
    subconfigs.vm.hostname="host2"
    subconfigs.vm.network :private_network, ip: "10.10.0.20"
    subconfigs.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
    subconfigs.vm.provision "shell", inline: <<-SHELL
    echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
    echo net.ipv4.ip_nonlocal_bind=1 >> /etc/sysctl.conf
    modprobe ip_vs
    SHELL
  end

  config.vm.define "web1" do |subconfigs|
    subconfigs.vm.box = "centos/7"
    subconfigs.vm.hostname="host1"
    subconfigs.vm.network :private_network, ip: "10.10.0.1"
    subconfigs.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
    subconfigs.vm.provision "shell", inline: <<-SHELL
    echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
    echo net.ipv4.ip_nonlocal_bind=1 >> /etc/sysctl.conf
    modprobe ip_vs
    SHELL
  end

  config.vm.define "web2" do |subconfigs|
    subconfigs.vm.box = "centos/7"
    subconfigs.vm.hostname="host2"
    subconfigs.vm.network :private_network, ip: "10.10.0.2"
    subconfigs.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
    subconfigs.vm.provision "shell", inline: <<-SHELL
    echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
    echo net.ipv4.ip_nonlocal_bind=1 >> /etc/sysctl.conf
    modprobe ip_vs
    SHELL
  end

  config.ssh.insert_key = false 
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"  

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "nginx_haproxy_ha.yml"
  end

end
