---
# tasks file for nginx
- name: NGINX | Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present
  tags:
    - epel-package
    - packages
- name: NGINX | Install NGINX package from EPEL Repo
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages

- name: NGINX | Create NGINX config file from template to web-1
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  copy:
    src: ../files/index_1.html
    dest: /usr/share/nginx/html/index.html
  notify:
    - reload nginx
  tags:
    - nginx-configuration
  when: ansible_hostname == "web1"

- name: NGINX | Create NGINX config file from template to web-1
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  copy:
    src: ../files/index_2.html
    dest: /usr/share/nginx/html/index.html
  notify:
    - reload nginx
  tags:
    - nginx-configuration
  when: ansible_hostname == "web2"