---
# tasks file for keepalived
- name: Keepalived Install package
  apt:
    name: keepalived
    state: present
  check_mode: true

- name: Keepalived configuration files for instance_1
  template:
    src: ../templates/keepalived_VI_1.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Keepalived start service
  service:
    name: keepalived
    state: started
    enabled: yes

- name: Keepalived add iptables rule
  ansible.builtin.iptables:
    chain: INPUT
    source: 224.0.0.0/8
    in_interface: enp0s8
    jump: ACCEPT
  become: yes

- name: Keepalived instance_1 add iptables rule
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_port: 112
    jump: ACCEPT
  become: yes
