---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - gnupg
    - python3-docker

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_apt_gpg }}" 
    state: present

- name: Add Docker repo
  apt_repository:
    repo: "{{ docker_apt_repo }}" 
    state: present
    update_cache: yes

- name: Update apt and install docker-ce debian
  apt:
    name: 
      - docker-ce
    update_cache: true
    state: latest

- name: Start Docker service debian
  service:
    name: docker
    state: started
    enabled: yes
