---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker GPG key
  ansible.builtin.rpm_key:
    key: "{{ docker_yum_gpg }}"
    state: present

- name: Add Docker repo
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "{{ docker_yum_repo }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ docker_yum_gpg }}"
    #state: present

- name: Install Docker
  package:
    name: 
      - docker-ce
      - containerd.io
    state: latest
    update_cache: yes

- name: Install docker-compose
  get_url:
    url : "{{ docker-compose_link }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
