---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  check_mode: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - gnupg
    - python3-docker

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_apt_gpg }}" 
    state: present

- name: Add Docker repo
  apt_repository:
    repo: "{{ docker_apt_repo }}" 
    state: present
    update_cache: yes

- name: Update apt and install docker-ce
  apt:
    name: 
      - docker-ce
    update_cache: true
    state: latest
  check_mode: true


#- name: Install Docker Module for Python
#  pip:
#    name: "{{ item }}"
#    state: present
#  check_mode: true
#  with_items:
#    - pip
#    - setuptools_rust
#    - wheel
#    - docker-compose

#- name: Install docker-compose
#  get_url:
#    url: https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-linux-x86_64
#    dest: /usr/local/bin/docker-compose
#    mode: 'u+x,g+x'

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
