---
- name: Add Docker GPG key
  ansible.builtin.rpm_key:
    key: "{{ docker_yum_gpg }}"
    state: present
    
- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: 'docker-ce-test'
    option: enabled
    value: 0

- name: Install Docker redhat
  yum:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python-docker-py
    - python3-pip
    - python-setuptools

- name: Start Docker service redhat
  service:
    name: docker
    state: started
    enabled: yes
